# Site settings
title: My Blog # site title
description: >- # site description
    Blog about documenting stuff that i learn/learnt.<a href="https://github.com/creator54" target="_blank" rel="noopener">@github</a>.
lang: en-IN # default lang
timezone: Asia/Kolkata # set your timezone
image: https://avatars3.githubusercontent.com/u/34543609?s=460&u=34f0f6c3ebc066d7519075e9cd4d8ad893ba7da1&v=4 # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/creator54/blogger/ # site repo [optional]
mode: dark # default theme "dark" | "light"

# Profile settings
author:
  name: Saroj Mahato  # author name
  bio: >- # tell to the world
    This Blog is for documenting stuff that i learn/learnt in the hope that it may help others and ofcourse the future me 😅.
  username: creator54 # general username
  linkedin: saroj-kumar-mahato #linkedin username
  email: mail@creator54.dev # email adress
  avatar: https://avatars3.githubusercontent.com/u/34543609?s=460&u=34f0f6c3ebc066d7519075e9cd4d8ad893ba7da1&v=4 # change with your own avatar

# URL settings
url: "https://creator54.dev" #
baseurl:
permalink: /:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 7

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec
  - assist.py

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-postfiles
